Install the Transformers, Datasets, and Evaluate libraries to run this notebook.

In [ ]:
!pip install datasets evaluate transformers[sentencepiece]

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 507.1/507.1 kB 5.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 6.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.3/115.3 kB 6.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 8.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 12.7 MB/s eta 0:00:00


In [ ]:
from transformers import pipeline

classifier = pipeline("sentiment-analysis")
classifier(
    [
        "I've been waiting for a HuggingFace course my whole life.",
        "I hate this so much!",
    ]
)

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

[{'label': 'POSITIVE', 'score': 0.9598048329353333},
 {'label': 'NEGATIVE', 'score': 0.9994558691978455}]

In [ ]:
from transformers import AutoTokenizer

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

In [ ]:
from transformers import AutoTokenizer

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

In [ ]:
raw_inputs = [
    """To Self-Justify is Human
Self-Serving Bias refers to a tendency for individuals to make dispositional attributions for their success and situational attributions for their failure. For example, in a social situation like an interview, if an interviewee named Reema nails the interview, chances are that she will attribute it to her intrinsic knowledge and negotiation skills. On the other hand, if she fails to pass it, she might claim that interviewer asked too difficult questions that anyone would have failed to answer or interviewer didn't seem to like her or in the worst case, that luck was not on her side. Researchers have gathered a great deal of evidence in support of the informal observation that we take credit for the good and deny the bad. This is not a lone case. Say for example you were travelling by a public bus and upon reaching the destination you realized that your phone is missing, you are likely to claim that someone has stolen it or you lost it because the bus was heavily crowded, instead of addressing your carelessness.
During the first outbreak of Covid-19, a mass exodus of migrant labourers occurred. One of the main reasons behind it was the fear that people had in their minds. It is also attributed as one of the chief reasons for the rife of the virus across states. There were indeed genuine concerns involved in this situation, but spread of fake news was also a contributing factor. Spreading of fake news is generally associated with people having vested interests. But this does not unveils the whole picture. People also spread fake news to justify their fears!
My goal here is not to analyse this situation from a political or economical stand-point. It is just to provide a relatable example for the readers to understand, "Why we as humans, tend to justify our actions, beliefs, and feelings?" from a social psychological stand-point and present the observations researchers made on the basis of data and surveys.
In the aftermath of an earthquake in India, investigators collected and analysed the rumours being spread. What they found was rather startling: when the disaster occurred in a neighborhoring village such that the residents in question could feel the tremors but were not in imminent danger, there was an abundance of rumours forecasting impending impending doom. The residents not only believed but also, helped spread rumours to the effect, that 1) a flood was rushing towards them; 2) Feb 26 would be a day of deluge and destruction; 3) there would another earthquake on the lunar eclipse and so on.
The kind of rumours spread in the case of earthquake case sound strikingly similar to what happened during the migrant labourer mass exodus outbreak, don't they? Perhaps, their cause of their spread also has some correlation!
Why on Earth would anyone in his right senses invent, believe, and communicate such stories? Were these people paranoids? Were these people masochists? Certainly these rumours would not encourage the people to feel calm and secured. One rather compelling explanation is that the people were terribly scared, and because there was not ample justification for this fear, they invented their own justification. Hence, they would not have to feel foolish in the eyes of the world. This explanation is bolstered by yet another study of rumours wherein it turned out that rumours spread in an Indian village directly affected by a disaster of similar magnitude was much less. People were scared, they had good reasons to be frightened; they had no need to seek additional justification for their fears.
Leon Festinger organized this array of findings and used them as the basis for a powerful theory of human motivation, the theory of cognitive dissonance. Cognitive dissonance is a state of tension that occurs whenever an individual simultaneously holds two cognitions ( ideas, attitudes, beliefs, opinions) that are psychologically consistent. Stated differently, two cognitions are dissonant if, when considered alone, the opposite of one follows from other. Because the occurrence of cognitive dissonance is unpleasant, people are motivated to reduce it. To hold two ideas that contradict with each other is to flirt with absurdity, and- as Albert Camus, the existentialist philosopher, has observed- humans are creatures who spend their lives trying to convince that existence is not absurd.
How do we convince ourselves that our lives are not absurd- that is, how do we reduce cognitive dissonance? By changing one or both cognitions in such a way to render them more compatible ( more consonant) with each other or by adding mote cognitions that help bridge the gap between the original cognitions.
Let's understand this with the help of a familiar example. Suppose a person consumes a lot of sugar and then reads a report of the medical evidence linking sugar consumption to diabetes. The person experiences dissonance. The cognition "I eat sugar" is dissonant with the cognition "excessive sugar causes diabetes." Clearly, the most efficient way for this person to reduce dissonance in such a situation is to give up sugar. The cognition "excessive sugar causes diabetes" is consonant with the cognition "I don't eat sugar. "
But, quitting sugar might not be very easy for people. What will they do reduce dissonance then? In all probability they will try to work on the other cognition.
A similar study was made about smoking in 1964, the evidence of smoking causes lung cancer was published. The survey indicated that 90% of the non smokers in the study justified and believed in the evidence ( their cognition was in consonance with the evidence). Smoking is a difficult habit to break; only 9% of the smokers had been able to quit. To justify the continuity of activity, smokers tried to debunk the report. They were likely to deny the evidence; 40% of the heavy smokers said a link had not been proven to exist. Over twice as many smokers as non smokers agreed that there are many hazards in life and both smokers and non smokers get cancer ( Again, attempts to reduce social dissonance).
(The concepts talked of here are backed by the findings from the book, Social Animal by Elliot Aronson.)"""
]
inputs = tokenizer(raw_inputs, padding=True, truncation=True, return_tensors="tf")
print(inputs)

{'input_ids': <tf.Tensor: shape=(1, 512), dtype=int32, numpy=
array([[  101,  2000,  2969,  1011, 16114,  2003,  2529,  2969,  1011,
         3529, 13827,  5218,  2000,  1037, 11765,  2005,  3633,  2000,
         2191, 22137,  2389,  2012, 18886, 29446,  2015,  2005,  2037,
         3112,  1998,  3663,  2389,  2012, 18886, 29446,  2015,  2005,
         2037,  4945,  1012,  2005,  2742,  1010,  1999,  1037,  2591,
         3663,  2066,  2019,  4357,  1010,  2065,  2019,  4357,  4402,
         2315,  2128, 14545, 10063,  1996,  4357,  1010,  9592,  2024,
         2008,  2016,  2097, 17961,  2009,  2000,  2014, 23807,  3716,
         1998, 19905,  4813,  1012,  2006,  1996,  2060,  2192,  1010,
         2065,  2016, 11896,  2000,  3413,  2009,  1010,  2016,  2453,
         4366,  2008,  4357,  2121,  2356,  2205,  3697,  3980,  2008,
         3087,  2052,  2031,  3478,  2000,  3437,  2030,  4357,  2121,
         2134,  1005,  1056,  4025,  2000,  2066,  2014,  2030,  1999,
         1996, 

In [ ]:
from transformers import TFAutoModel

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
model = TFAutoModel.from_pretrained(checkpoint)

In [ ]:
from transformers import TFAutoModel  ## this class does not output probabilities

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
model = TFAutoModel.from_pretrained(checkpoint)

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFDistilBertModel: ['pre_classifier.bias', 'classifier.weight', 'pre_classifier.weight', 'classifier.bias']
- This IS expected if you are initializing TFDistilBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFDistilBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertModel for predictions without further training.


In [ ]:
outputs = model(inputs)
print(outputs.last_hidden_state.shape)


(1, 512, 768)


TFBaseModelOutput(last_hidden_state=<tf.Tensor: shape=(1, 512, 768), dtype=float32, numpy=
array([[[-0.52952105,  0.63451123, -0.26126066, ..., -0.20760374,
         -0.05900528,  0.44516516],
        [-0.6319397 ,  1.1988682 , -0.92183185, ..., -0.12525909,
          0.34233552,  0.21901056],
        [-0.7316502 ,  1.2097225 , -0.611805  , ..., -0.12666723,
          0.2312656 ,  0.35935473],
        ...,
        [-0.569224  ,  0.2583691 , -0.35569394, ..., -0.4098876 ,
          0.20684338,  0.10301369],
        [-0.37700173, -0.01081326, -0.22857094, ..., -0.15479293,
         -0.00494558, -0.57931185],
        [-0.27692807,  1.1092331 , -0.2298873 , ...,  0.05823718,
         -0.3207901 , -0.29498342]]], dtype=float32)>, hidden_states=None, attentions=None)

In [ ]:
from transformers import TFAutoModelForSequenceClassification ## transformer library has modules like this for each nlp task

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
model = TFAutoModelForSequenceClassification.from_pretrained(checkpoint)
outputs = model(inputs)

All PyTorch model weights were used when initializing TFDistilBertForSequenceClassification.

All the weights of TFDistilBertForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForSequenceClassification for predictions without further training.


In [ ]:
print(outputs.logits.shape)

(1, 2)


In [ ]:
print(outputs.logits)

tf.Tensor([[ 2.4570172 -2.077541 ]], shape=(1, 2), dtype=float32)


In [ ]:
import tensorflow as tf

predictions = tf.math.softmax(outputs.logits, axis=-1)
print(predictions)

tf.Tensor([[0.98938227 0.0106177 ]], shape=(1, 2), dtype=float32)


In [ ]:
model.config.id2label

{0: 'NEGATIVE', 1: 'POSITIVE'}

In [ ]:
##Model Predicts 98% negative sentiment, let's  try another model

In [3]:
from transformers import TFAutoModelForSequenceClassification, AutoTokenizer


In [4]:
checkpoint2 = 'ProsusAI/finbert'
tokenizer= AutoTokenizer.from_pretrained(checkpoint2)

tokenizer_config.json:   0%|          | 0.00/252 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/758 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [5]:
raw_inputs = [
    """To Self-Justify is Human
Self-Serving Bias refers to a tendency for individuals to make dispositional attributions for their success and situational attributions for their failure. For example, in a social situation like an interview, if an interviewee named Reema nails the interview, chances are that she will attribute it to her intrinsic knowledge and negotiation skills. On the other hand, if she fails to pass it, she might claim that interviewer asked too difficult questions that anyone would have failed to answer or interviewer didn't seem to like her or in the worst case, that luck was not on her side. Researchers have gathered a great deal of evidence in support of the informal observation that we take credit for the good and deny the bad. This is not a lone case. Say for example you were travelling by a public bus and upon reaching the destination you realized that your phone is missing, you are likely to claim that someone has stolen it or you lost it because the bus was heavily crowded, instead of addressing your carelessness.
During the first outbreak of Covid-19, a mass exodus of migrant labourers occurred. One of the main reasons behind it was the fear that people had in their minds. It is also attributed as one of the chief reasons for the rife of the virus across states. There were indeed genuine concerns involved in this situation, but spread of fake news was also a contributing factor. Spreading of fake news is generally associated with people having vested interests. But this does not unveils the whole picture. People also spread fake news to justify their fears!
My goal here is not to analyse this situation from a political or economical stand-point. It is just to provide a relatable example for the readers to understand, "Why we as humans, tend to justify our actions, beliefs, and feelings?" from a social psychological stand-point and present the observations researchers made on the basis of data and surveys.
In the aftermath of an earthquake in India, investigators collected and analysed the rumours being spread. What they found was rather startling: when the disaster occurred in a neighborhoring village such that the residents in question could feel the tremors but were not in imminent danger, there was an abundance of rumours forecasting impending impending doom. The residents not only believed but also, helped spread rumours to the effect, that 1) a flood was rushing towards them; 2) Feb 26 would be a day of deluge and destruction; 3) there would another earthquake on the lunar eclipse and so on.
The kind of rumours spread in the case of earthquake case sound strikingly similar to what happened during the migrant labourer mass exodus outbreak, don't they? Perhaps, their cause of their spread also has some correlation!
Why on Earth would anyone in his right senses invent, believe, and communicate such stories? Were these people paranoids? Were these people masochists? Certainly these rumours would not encourage the people to feel calm and secured. One rather compelling explanation is that the people were terribly scared, and because there was not ample justification for this fear, they invented their own justification. Hence, they would not have to feel foolish in the eyes of the world. This explanation is bolstered by yet another study of rumours wherein it turned out that rumours spread in an Indian village directly affected by a disaster of similar magnitude was much less. People were scared, they had good reasons to be frightened; they had no need to seek additional justification for their fears.
Leon Festinger organized this array of findings and used them as the basis for a powerful theory of human motivation, the theory of cognitive dissonance. Cognitive dissonance is a state of tension that occurs whenever an individual simultaneously holds two cognitions ( ideas, attitudes, beliefs, opinions) that are psychologically consistent. Stated differently, two cognitions are dissonant if, when considered alone, the opposite of one follows from other. Because the occurrence of cognitive dissonance is unpleasant, people are motivated to reduce it. To hold two ideas that contradict with each other is to flirt with absurdity, and- as Albert Camus, the existentialist philosopher, has observed- humans are creatures who spend their lives trying to convince that existence is not absurd.
How do we convince ourselves that our lives are not absurd- that is, how do we reduce cognitive dissonance? By changing one or both cognitions in such a way to render them more compatible ( more consonant) with each other or by adding mote cognitions that help bridge the gap between the original cognitions.
Let's understand this with the help of a familiar example. Suppose a person consumes a lot of sugar and then reads a report of the medical evidence linking sugar consumption to diabetes. The person experiences dissonance. The cognition "I eat sugar" is dissonant with the cognition "excessive sugar causes diabetes." Clearly, the most efficient way for this person to reduce dissonance in such a situation is to give up sugar. The cognition "excessive sugar causes diabetes" is consonant with the cognition "I don't eat sugar. "
But, quitting sugar might not be very easy for people. What will they do reduce dissonance then? In all probability they will try to work on the other cognition.
A similar study was made about smoking in 1964, the evidence of smoking causes lung cancer was published. The survey indicated that 90% of the non smokers in the study justified and believed in the evidence ( their cognition was in consonance with the evidence). Smoking is a difficult habit to break; only 9% of the smokers had been able to quit. To justify the continuity of activity, smokers tried to debunk the report. They were likely to deny the evidence; 40% of the heavy smokers said a link had not been proven to exist. Over twice as many smokers as non smokers agreed that there are many hazards in life and both smokers and non smokers get cancer ( Again, attempts to reduce social dissonance).
(The concepts talked of here are backed by the findings from the book, Social Animal by Elliot Aronson.)"""
]
inputs = tokenizer(raw_inputs, padding=True, truncation=True, return_tensors="tf")
print(inputs)

{'input_ids': <tf.Tensor: shape=(1, 512), dtype=int32, numpy=
array([[  101,  2000,  2969,  1011, 16114,  2003,  2529,  2969,  1011,
         3529, 13827,  5218,  2000,  1037, 11765,  2005,  3633,  2000,
         2191, 22137,  2389,  2012, 18886, 29446,  2015,  2005,  2037,
         3112,  1998,  3663,  2389,  2012, 18886, 29446,  2015,  2005,
         2037,  4945,  1012,  2005,  2742,  1010,  1999,  1037,  2591,
         3663,  2066,  2019,  4357,  1010,  2065,  2019,  4357,  4402,
         2315,  2128, 14545, 10063,  1996,  4357,  1010,  9592,  2024,
         2008,  2016,  2097, 17961,  2009,  2000,  2014, 23807,  3716,
         1998, 19905,  4813,  1012,  2006,  1996,  2060,  2192,  1010,
         2065,  2016, 11896,  2000,  3413,  2009,  1010,  2016,  2453,
         4366,  2008,  4357,  2121,  2356,  2205,  3697,  3980,  2008,
         3087,  2052,  2031,  3478,  2000,  3437,  2030,  4357,  2121,
         2134,  1005,  1056,  4025,  2000,  2066,  2014,  2030,  1999,
         1996, 

In [13]:
from transformers import TFAutoModelForSequenceClassification ## transformer library has modules like this for each nlp task
checkpoint2 = 'ProsusAI/finbert'
model = TFAutoModelForSequenceClassification.from_pretrained(checkpoint2)
outputs = model(inputs)

tf_model.h5:   0%|          | 0.00/438M [00:00<?, ?B/s]

All model checkpoint layers were used when initializing TFBertForSequenceClassification.

Some layers of TFBertForSequenceClassification were not initialized from the model checkpoint at ProsusAI/finbert and are newly initialized: ['classifier']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [14]:
outputs.logits

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[ 0.12715031,  0.40099797, -0.18528822]], dtype=float32)>

In [15]:
import tensorflow as tf

predictions = tf.math.softmax(outputs.logits, axis=-1)
print(predictions)

tf.Tensor([[0.32822666 0.4316228  0.24015053]], shape=(1, 3), dtype=float32)


In [16]:
model.config.id2label

{0: 'positive', 1: 'negative', 2: 'neutral'}

In [ ]:
#The model is predicted 43% negative